name: iOS Build Test

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-15
    env:
      SECRET_XCCONFIG_PATH: PpuDaeSik/Projects/Logger/Configurations/Secrets.xcconfig
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Tuist via Homebrew
        run: |
          brew install tuist
          tuist version

      - name: Tuist Generate
        working-directory: ./PpuDaeSik
        run: |
          tuist generate --no-open

      - name: Create Secrets
        run: |
          echo "${{ secrets.SECRETS_XCCONFIG }}" > ${{ env.SECRET_XCCONFIG_PATH }}

      # === (1) tuist generate and build test ===
      - name: Build App target from xcworkspace
        working-directory: ./PpuDaeSik
        run: |
          set -o pipefail

          xcodebuild clean build \
            -workspace PpuDaeSik.xcworkspace \
            -scheme PpuDaeSik \
            -destination "platform=iOS Simulator,OS=18.0,name=iPhone 16 Pro" \
            | xcpretty

      # === (2) tuist test ===
      - name: Run Tests with Tuist
        working-directory: ./PpuDaeSik
        run: |
          tuist test --platform ios
